### ISSUE TITLE
"github.com/segmentio/stats/v4" missing?

### ISSUE THREAD

**Issue by andrijaa** [segmentio/stats#115]
Hello there,
I might be missing something obvious, but I am having issues using v4 version of segmentio. i was trying to download it and use it in my go project, but I don't see it anywhere

Lots of files, like in "httpstats" folder  reference "github.com/segmentio/stats/v4/" but it is nowhere to be found. 

Ideas? Thank you!

**Comment by achille-roussel** [comment]
The `/v4` part is the major version number interpreted by go modules. You can see in the releases that the latest version is v4.5.2 https://github.com/segmentio/stats/releases, that's where the v4 is picked from.

**Comment by andrijaa** [comment]
Ah gotcha that makes sense. thanks
