### ISSUE TITLE
stats ticker?

### ISSUE THREAD

**Issue by yields** [segmentio/stats#28]
I believe this is incredibly useful for workers, so we know the worker is doing _something_.
Its true that its possible to just look at the dash, but when debugging its useful (locally or otherwise).

```
stats 2014/07/18 11:24:27 messages 94.00/s tick=470 total=470
stats 2014/07/18 11:24:27 errors 18.80/s tick=94 total=94
stats 2014/07/18 11:24:32 messages 96.98/s tick=485 total=955
stats 2014/07/18 11:24:32 errors 19.40/s tick=97 total=191
stats 2014/07/18 11:24:37 messages 98.99/s tick=495 total=1450
stats 2014/07/18 11:24:37 errors 19.80/s tick=99 total=290
```

@achille-roussel for thoughts, before i go ahead and implement in vain haha

**Comment by achille-roussel** [comment]
Isn't it the responsibility of logs to output information about program execution?

If you want to capture the stats output you can run `segment/dogstatsd` side-by-side (with docker-compose for example), and you get all your stats in the logs of that container. Do you think that would address your use case?

**Comment by yields** [comment]
> If you want to capture the stats output you can run segment/dogstatsd side-by-side (with docker-compose for example), and you get all your stats in the logs of that container. Do you think that would address your use case?

It does in _development_, it's not a problem to implement this as a separate library or in the worker itself, i just thought this project would benefit from `./logstats` package or similar.

**Comment by achille-roussel** [comment]
Does it make sense to log stats calls in production tho? This doesn't strike me as a good design. If there are things that are interesting for the operator to know about what the program is doing it's unlikely to be that the stats are being sent.
During development tho, it's good for the developer to be able to verify that the full stats stack is working, which is why I think the solution of running `segment/dogstatsd` is more appealing that outputting stats info to the logs.

**Comment by yields** [comment]
> Does it make sense to log stats calls in production tho? This doesn't strike me as a good design. If there are things that are interesting for the operator to know about what the program is doing it's unlikely to be that the stats are being sent.

I agree that it doesn't make sense, but i think it is still useful -- Especially for operators that are not familiar with the software they're trying to fix.

I've seen this multiple times during fires, you're trying to figure out if the worker is doing something but it logs nothing, workers don't log anything really, unless there are errors.

Imagine this:

```golang
eng := stats.NewEngine()
eng.Register(datadog.NewClient(addr))
eng.Register(logstats.NewEvery(time.Second * 5))
defer eng.Flush()
```

I think in cases where you're trying to figure out if a worker actually works properly you'll be glad stats are logged every 5s.

I personally saw this with some of our stuff, where i would start something only for it to log nothing, and then i'm left wondering if it actually works. Obviously i could just check datadog, but the feedback loop there is slower, especially when you're trying to put out a fire.

**Comment by achille-roussel** [comment]
The worker not logging anything is not a stats problem tho, it has to do with the code being poorly designed and the reviewer not having required that something get logged to give a good understanding of the program's behavior.

As an operator, if I check the logs of a service and all I see are generic info about the number of stats being sent it gives me absolutely no signal and is as good as not having any logs. For example, the procstats sub=package collects metrics on the program periodically, and therefore has to run in a separate goroutine. If the program is not doing anything, you'd still see plenty of stats messages going through, but you have no info about what those messages are. In this case, it would mislead you into thinking the program is producing work when in fact it's not.

I understand your concern but I really feel like this is the wrong way to address the problem, this is an issue with people not knowing how to write good logs.

PS: I've been thinking about giving a talk on how to write logs for a while ;)

**Comment by yields** [comment]
> The worker not logging anything is not a stats problem tho, it has to do with the code being poorly designed and the reviewer not having required that something get logged to give a good understanding of the program's behavior.

What would you log from a worker that doesn't hit any error cases?

**Comment by achille-roussel** [comment]
In development, you'd log meaningful traces about what the program is doing, things like HTTP access logs.

In production, you want to show anything that's interesting to know for the operator, usually these are special events that happen in the program. Opening/Closing connections, errors, signals, etc... The operator will look at the stats and be able to get insights in the "normal" work being produced, and if the stats are at zero, then it's not doing anything.

**Comment by yields** [comment]
We discussed this offline and agreed that workers can just use loglevels and implement signals on `SIGUSR1` `SIGUSR2` to toggle debug mode.
