### ISSUE TITLE
procstats kills process?

### ISSUE THREAD

**Issue by matthewmueller** [segmentio/stats#44]
Hey there. I'm running into procstats immediately killing the process on OSX. Here's the code I'm running

```go
var prom = prometheus.DefaultHandler

func main() {
	log.SetHandler(text.New(os.Stderr))
	stats.Register(prom)

	c := procstats.StartCollector(procstats.NewGoMetrics())
	defer c.Close()

	router := httprouter.New()
	router.Handler("GET", "/", httpstats.NewHandler(http.HandlerFunc(index)))
	router.Handler("GET", "/metrics", http.HandlerFunc(prom.ServeHTTP))

	log.Infof("listening on http://localhost:9000")
	log.WithError(http.ListenAndServe(":9000", router)).Fatal("server died")
}

func index(w http.ResponseWriter, r *http.Request) {
	stats.Incr("visited index")
	defer stats.Time("timing you", time.Now()).Stop()
	w.Write([]byte("hi world!"))
}
```

And this is what I'm seeing:

```bash
go run stats.go
signal: killed
```

Is this intentional?

**Comment by ivolo** [comment]
hey @matthewmueller why are you up at 3am PST :)

**Comment by achille-roussel** [comment]
This is not intentional and it's the first time I'm getting this reported. The package doesn't send signals itself so this is weird. I'll try to repro later today.

In the mean time, if you can gather more info? Like trying to run the same code without the procstats.StartCollector call for example.

Also what version of Go are you running?

**Comment by matthewmueller** [comment]
@ivolo I'm in Asia 😆  I should be asking you guys that! Late night at the office?

@achille-roussel It's **very** odd, if I add anything related to procstats I hit it. Even if I do:

```
func main () {
  fmt.Println(procstats.CPUInfo{})
}
```

I get a SIGKILL. Could this be related to cgo? I've tried reinstalling it via `go get`, but no luck there.

```
go version go1.8.3 darwin/amd64
```

**Comment by matthewmueller** [comment]
Okay sorry for the false alarm. It looks like it's due to this issue: https://github.com/golang/go/issues/19734
