### ISSUE TITLE
procstats fails to compile on OS X 10.11.6

### ISSUE THREAD

**Issue by f2prateek** [segmentio/stats#71]
Running `go test ./...` on master (3de5f65) fails for the procstats package:

```
# github.com/segmentio/stats/procstats
could not determine kind of name for C.task_inspect_t
```

https://cloudup.com/c4049ggaVsX

**Comment by thehydroimpulse** [comment]
cc @achille-roussel 

I'm also getting this error while trying to build centrifuge.

**Comment by thehydroimpulse** [comment]
@f2prateek you need to upgrade OSX/XCode for this to work. It was added in 10.12.4.
