### ISSUE TITLE
Per request tags

### ISSUE THREAD

**Issue by mnichols** [segmentio/stats#93]
Hi we are using the `httpstats` Transport decorator like this:

```
	tags := []stats.Tag{
                // this tag is OK to always be the same value
		{Name: TagCallingService, Value: opts.CallingService},
                // but this tag should be determined by some properties of the outbound request
		{Name: TagRequestName, Value: computeRequestName()},
	}

	return httpstats.NewTransportWith(stats.DefaultEngine.WithTags(tags...), inner)
```

However, we need to provide a couple of tags with values determined by the request (based on the path, etc). It seems to be bad practice to create a new client / transport per request but the `httpstats` Transport decorator doesnt seem to provide a way to add a couple of tags during a request.
Is there some kind of callback or hook for adding tags that are scoped to a request?

**Comment by abraithwaite** [comment]
Fixed by #104 and #111.
